using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WorldDi.TapePlayer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._WorldDi.TapePlayer.UI;

[GenerateTypedNameReferences]
public sealed partial class TapePlayerWindow : FancyWindow
{
    public EntityUid Owner;

    private bool _isPlaying;
    private float _songLength;
    private bool _updating;
    private float _lockTimer;
    private string _currentCategory = string.Empty;
    private string _currentSongId = string.Empty;
    private readonly HashSet<string> _expandedCategories = new();

    public Action? OnPlayPressed;
    public Action? OnStopPressed;
    public Action<float>? OnVolumeChanged;
    public Action<float>? OnPositionChanged;
    public Action<string>? OnCategorySelected;
    public Action<string>? OnSongSelected;

    public TapePlayerWindow()
    {
        RobustXamlLoader.Load(this);

        PlayButton.OnPressed += _ => OnPlayPressed?.Invoke();
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();

        PlaybackSlider.OnReleased += args =>
        {
            if (_lockTimer > 0f)
                return;
            OnPositionChanged?.Invoke(PlaybackSlider.Value);
            _lockTimer = 0.3f;
        };

        VolumeSlider.OnReleased += args =>
        {
            if (_lockTimer > 0f)
                return;
            OnVolumeChanged?.Invoke(VolumeSlider.Value / 100f);
            _lockTimer = 0.3f;
        };
    }

    public void SetPlayPauseButton(bool playing)
    {
        _isPlaying = playing;
        PlayButton.Text = Loc.GetString(playing
            ? "tape-player-menu-button-pause"
            : "tape-player-menu-button-play");
    }

    public void UpdateState(TapePlayerState state)
    {
        _updating = true;

        _songLength = state.SongLength;
        _currentCategory = state.CurrentCategory;
        _currentSongId = state.CurrentSongId;

        SongNameLabel.Text = string.IsNullOrEmpty(state.CurrentSongName)
            ? "---"
            : state.CurrentSongName;

        SetPlayPauseButton(state.Mode == TapePlayerPlayMode.Playing);

        PlayButton.Disabled = string.IsNullOrEmpty(state.CurrentSongId);
        StopButton.Disabled = string.IsNullOrEmpty(state.CurrentSongId);

        VolumeSlider.SetValueWithoutEvent(state.Volume * 100f);
        PlaybackSlider.MaxValue = state.SongLength > 0 ? state.SongLength : 1f;

        BuildCategoryTree(state.CategoryTree);
        BuildSongTree(state.SongTree);

        _updating = false;
    }

    public void UpdatePlaybackPosition(float position)
    {
        if (PlaybackSlider.Grabbed || _lockTimer > 0f)
            return;

        PlaybackSlider.SetValueWithoutEvent(position);

        var current = TimeSpan.FromSeconds(position);
        var total = TimeSpan.FromSeconds(_songLength);
        DurationLabel.Text = $@"{current:mm\:ss} / {total:mm\:ss}";
    }

    private void BuildCategoryTree(List<TapeCategoryTreeEntry> roots)
    {
        CategoryTree.RemoveAllChildren();

        var allButton = new Button
        {
            Text = Loc.GetString("tape-player-category-all"),
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left,
        };

        var isAllSelected = string.IsNullOrEmpty(_currentCategory);
        allButton.ModulateSelfOverride = isAllSelected
            ? new Color(0.4f, 0.8f, 1.0f, 1.0f)
            : Color.White;

        allButton.OnPressed += _ =>
        {
            if (!_updating)
                OnCategorySelected?.Invoke(string.Empty);
        };

        CategoryTree.AddChild(allButton);

        foreach (var root in roots)
        {
            AddCategoryNode(CategoryTree, root, 0);
        }
    }

    private void AddCategoryNode(BoxContainer parent, TapeCategoryTreeEntry node, int depth)
    {
        var hasChildren = node.Children.Count > 0;
        var isExpanded = _expandedCategories.Contains(node.Id);
        var isSelected = _currentCategory == node.Id;

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var indent = new Control
        {
            MinSize = new Vector2(depth * 16, 0),
        };
        container.AddChild(indent);

        if (hasChildren)
        {
            var expandBtn = new Button
            {
                Text = isExpanded ? "\u25BC" : "\u25B6",
                MinSize = new Vector2(20, 0),
                TextAlign = Label.AlignMode.Center,
            };

            expandBtn.OnPressed += _ =>
            {
                if (isExpanded)
                    _expandedCategories.Remove(node.Id);
                else
                    _expandedCategories.Add(node.Id);

                RebuildState();
            };

            container.AddChild(expandBtn);
        }
        else
        {
            var spacer = new Control
            {
                MinSize = new Vector2(20, 0),
            };
            container.AddChild(spacer);
        }

        var btn = new Button
        {
            Text = node.DisplayName,
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left,
        };

        if (isSelected)
        {
            btn.ModulateSelfOverride = new Color(0.4f, 0.8f, 1.0f, 1.0f);
        }

        btn.OnPressed += _ =>
        {
            if (!_updating)
                OnCategorySelected?.Invoke(node.Id);
        };

        container.AddChild(btn);
        parent.AddChild(container);

        if (hasChildren && isExpanded)
        {
            foreach (var child in node.Children)
            {
                AddCategoryNode(parent, child, depth + 1);
            }
        }
    }

    private void BuildSongTree(List<TapeSongTreeEntry> songs)
    {
        SongTree.RemoveAllChildren();

        var allBtn = new Button
        {
            Text = Loc.GetString("tape-player-song-all"),
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left,
        };

        allBtn.OnPressed += _ =>
        {
            if (!_updating)
                OnSongSelected?.Invoke(string.Empty);
        };

        SongTree.AddChild(allBtn);

        foreach (var song in songs)
        {
            var isSelected = _currentSongId == song.Id;

            var btn = new Button
            {
                Text = song.DisplayName,
                HorizontalExpand = true,
                TextAlign = Label.AlignMode.Left,
            };

            if (isSelected)
            {
                btn.ModulateSelfOverride = new Color(0.4f, 0.8f, 1.0f, 1.0f);
            }

            btn.OnPressed += _ =>
            {
                if (!_updating)
                    OnSongSelected?.Invoke(song.Id);
            };

            SongTree.AddChild(btn);
        }
    }

    private void RebuildState()
    {
        // Trigger rebuild by re-sending category selection
        OnCategorySelected?.Invoke(_currentCategory);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
            _lockTimer -= args.DeltaSeconds;

        PlaybackSlider.Disabled = _lockTimer > 0f || string.IsNullOrEmpty(_currentSongId);
        VolumeSlider.Disabled = _lockTimer > 0f;
    }
}
